//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA
    {
        public int ID_Cita { get; set; }
        public string Rut_usuario { get; set; }
        public int ID_mascota { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
    
        public virtual MASCOTA MASCOTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
