//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int ID_Cita { get; set; }
        public string Rut_Usuario { get; set; }
        public int ID_Mascota { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
