//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta
    {
        public Boleta()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int ID_Venta { get; set; }
        public string Rut_Usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public int Total_Venta { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
