//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dueño
    {
        public Dueño()
        {
            this.Mascota = new HashSet<Mascota>();
        }
    
        public string Rut_dueño { get; set; }
        public string Estado_Dueño { get; set; }
        public string nombre { get; set; }
        public string apell_pat { get; set; }
        public string apell_mat { get; set; }
    
        public virtual ICollection<Mascota> Mascota { get; set; }
    }
}
