//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASCOTA
    {
        public MASCOTA()
        {
            this.AGENDA = new HashSet<AGENDA>();
        }
    
        public int ID_mascota { get; set; }
        public string Rut_dueño { get; set; }
        public bool Estado_mascota { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public string raza { get; set; }
        public int edad { get; set; }
    
        public virtual ICollection<AGENDA> AGENDA { get; set; }
        public virtual DUEÑOS DUEÑOS { get; set; }
    }
}
