//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public Mascota()
        {
            this.Agenda = new HashSet<Agenda>();
        }
    
        public int ID_Mascota { get; set; }
        public string Rut_Dueño { get; set; }
        public string Estado_Mascota { get; set; }
        public string Nombre { get; set; }
        public string tipo { get; set; }
        public string raza { get; set; }
        public int edad { get; set; }
    
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual Dueño Dueño { get; set; }
    }
}
