//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public PRODUCTOS()
        {
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public int ID_Producto { get; set; }
        public bool Estado_producto { get; set; }
        public string Nombre { get; set; }
        public int Stock { get; set; }
        public decimal Precio_unidad { get; set; }
    
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
