//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.AGENDA = new HashSet<AGENDA>();
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public string Rut_usuario { get; set; }
        public bool Estado_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<AGENDA> AGENDA { get; set; }
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
