//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Agenda = new HashSet<Agenda>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public string Rut_Usuario { get; set; }
        public string Estado_Usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string password { get; set; }
        public string rol_usuario { get; set; }
    
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
