//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public int ID_venta { get; set; }
        public string Rut_usuario { get; set; }
        public int ID_producto { get; set; }
        public System.DateTime Fecha_hora { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio_unidad { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
