//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diego_Herrera___Prueba_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinariaEntities : DbContext
    {
        public VeterinariaEntities()
            : base("name=VeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agenda> Agenda { get; set; }
        public DbSet<Dueño> Dueño { get; set; }
        public DbSet<Mascota> Mascota { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Ventas> Ventas { get; set; }
    }
}
